### PR TITLE
[WIP] Modify project files

### PR DESCRIPTION
**Pull request by tomlokhorst**
This is a work in progress to allow for modification of PBXProject files.
- [x] Move from classes to protocols
- [x] Create structs to implement the protocols
- [ ] Use struct values when serializing
- [ ] Refactor code, move functions and extensions to correct files
- [x] Don't crash, but gracefully fallback for unknown subclasses of PBXObject (e.g. a new type of build phase)
- [ ] Allow for modification of struct fields
- [ ] Allow for entirely new values (generate ids)
- [x] Drastically improve performance (a big test project I have currently takes 80 seconds to serialize)

### CODE REVIEW

**Comment by cezheng** [comment]
:+1:

**Comment by cezheng** [comment]
Nice job! I've been using https://github.com/appsquickly/XcodeEditor so far for a project that needs to modify Xcode projects, which serialize the project into xml plist format producing a large diff. I've tested the master branch and with a little bit modifications on PBXHeaderBuildPhase, this project can almost produce no diff which is so great. 

I've tried loading the DVTFoundation.framework etc. to let Xcode serialize the project, but that is too heavy and will crash if the project is not a OSX command line tool.

I think for the time being, I will use this project just to reserialize the project. Hopefully I will be able to remove XcodeEditor soon.

**Comment by tomlokhorst** [comment]
Thanks!

I hadn't even thought of using something external like XcodeEditor (or even `plutil`) to modify the file and have Xcode.swift reserialize to OpenStep format. That's a great idea!

What do you mean by "this project can almost produce no diff"? Was the diff something you introduced by your modification, or was it an accidental diff introduced by Xcode.swift? My goal is to have no diffs at all, if you're not modifying the pbxproj file.

**Comment by cezheng** [comment]
@tomlokhorst 
The serialization produced some diffs in the comment part of the Headers build phase. I added this line:
https://github.com/tomlokhorst/Xcode.swift/compare/develop...cezheng:fix/remove_diff_in_PBXHeaderBuildPhase?expand=1
 and no more diffs were produced for this project file:
https://github.com/cezheng/Fuzi/blob/master/Fuzi.xcodeproj/project.pbxproj

**Comment by cezheng** [comment]
I was just about to make a PR for this then I saw this PR which has greatly changed the project's directory structure

**Comment by cezheng** [comment]
Also, I just realized that this project is causing the example program to crash
https://github.com/cocos2d/cocos2d-x/blob/v3/templates/cpp-template-default/proj.ios_mac/HelloCpp.xcodeproj/project.pbxproj#L429

due to /\* Begin PBXReferenceProxy section */

**Comment by tomlokhorst** [comment]
Thanks for these two projects. Apparently none of my test projects use a PBXHeaderBuildPhase.

I'll add the PBXReferenceProxy type to the develop branch. Then I'll merge develop back into this pull request.

Hopefully I now have all PBX\* types covered, but I'll compare this to the class listings in some similar tools to double check.

**Comment by tomlokhorst** [comment]
This PR is outdated and doesn't work anymore with XcodeEdit 2.0.

It's best to reimplement this again.

**Pull request closed without merging**
